# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"

  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :test do
   run_tests(scheme: "DevOpsDemoApp",
   output_directory: "./test_output")
  end

  lane :build do
   sh("echo building app > build.log")
  end

 	
  lane :info do
    puts "Application Name: #{ENV['APP_NAME']}"
    puts "Version: #{ENV['APP_VERSION']}" 
  end

  lane :secrets_check do
    if ENV['API_KEY']
	puts "Secretes received successfully"
    else 
        puts "Secret missing"
    end
  end


  lane :deploy do
     environment = ENV['DEPLOY_ENV']
     puts "Starting Deployment"	
     puts "Deploying to #{environment}"
     sh("mkdir -p deploy_output")
     sh("echo Deployment to #{environment} successful > deploy_output/deploy.log")

  end


end
