name: iOS CI

on:
    push:
        branches:
            - main
            
jobs:
    test:
      runs-on: macos-latest

    build:
      needs: test
      runs-on: macos-latest
    
    steps:
        - uses: actions/checkout@v3
        
        - uses: ruby/setup-ruby@v1
            with:
                ruby-version: '3.2'
        - run: gem install fastlane
        
        - run: fastlane test

