name: Main CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    
jobs:
    call-test:
        uses: ./.github/workflows/reusable-test.yml
        with:
        with:
            environment: staging
